openapi: 3.0.1
info:
  title: Identity
  description: All included utility endpoints for Basiq partners
  version: 3.0.0
  termsOfService: 'https://docs.basiq.io/en/collections/440849-privacy-terms-and-common-questions'
  license: 
    name: Basiq
    url: https://basiq.io   
servers:
  - url: https://au-api.basiq.io
paths:
  /users/{userId}/identities:
    get:
      tags:
      - Identities
      summary: Retrieve identities
      description: Returns a list with a data property that contains an array of user
        identities. Each entry in the array is a separate object. If no data is returned,
        the resulting array will be empty.
      operationId: getUserIdentities
      parameters:
      - name: userId
        in: path
        description: User identifier.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Returns list of identities.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentitiesGetResponseResource'
        400:
          description: Returns error that server cannot or will not process the request
            due to something that is perceived to be a client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                    Bad Request:
                     value:
                      type: list
                      correlationId: ac5ah5i
                      data:
                        - type: error
                          title: Parameter not valid.
                          code: parameter-not-valid
                          detail: ID value is not valid.
                          source:
                            parameter: id
                    Invalid Filters:
                      value:
                        type: list
                        correlationId: ac5ah55
                        data:
                          - type: error
                            code: parameter-not-valid
                            title: Parameter value is not valid
                            detail: The provided filter parameter is in invalid format or unsupported
                            source:
                              parameter: filter
        403:
          description: Error that access is forbidden and tied to the application
            logic, such as insufficient rights to a resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenAccessError'
        500:
          description: Returns error response code indicates that the server encountered
            an unexpected condition that prevented it from fulfilling the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      security:
      - services_token: []
  /users/{userId}/identities/{identityId}:
    get:
      tags:
      - Identities
      summary: Retrieve an identity
      description: Returns a specific identity object.
      operationId: getUserIdentity
      parameters:
      - name: userId
        in: path
        description: User identifier.
        required: true
        schema:
          type: string
      - name: identityId
        in: path
        description: Identity identifier.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Returns identity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentityData'
        400:
          description: Returns error that server cannot or will not process the request
            due to something that is perceived to be a client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        403:
          description: Error that access is forbidden and tied to the application
            logic, such as insufficient rights to a resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenAccessError'
        404:
          description: Returns error indicating that server can't find requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        500:
          description: Returns error response code indicates that the server encountered
            an unexpected condition that prevented it from fulfilling the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      security:
      - services_token: []
components:
  schemas:
    BadRequestError:
      required:
        - correlationId
        - data
        - type
      type: object
      properties:
        type:
          type: string
          description: Always "list".
          example: list
        correlationId:
          type: string
          description: Unique identifier for this particular occurrence of the problem.
          example: ac5ah5i
        data:
          type: array
          description: Error data.
          items:
            required:
              - code
              - type
            type: object
            properties:
              type:
                type: string
                description: Type of the response, always "error"
                example: error
              title:
                type: string
                description: Title of the error
                example: Parameter not valid.
              code:
                type: string
                description: Application-specific error code, expressed as a string value.
                example: parameter-not-valid
                enum:
                  - parameter-not-supplied
                  - parameter-not-valid
                  - unsupported-accept
                  - invalid-content
                  - institution-not-supported
                  - invalid-credentials
              detail:
                type: string
                description: >-
                  Human-readable explanation specific to this occurrence of the
                  problem.
                example: ID value is not valid.
              source:
                $ref: '#/components/schemas/Source'
    IdentitiesGetResponseResource:
      title: IdentitiesGetResponseResource
      required:
      - count
      - data
      - type
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/IdentityData'
        type:
          type: string
          description: Type, always "list".
          example: list
        count:
          type: integer
          description: Count of the identities in the response.
          format: int64
          example: 100
      description: Object containing details for identities.
    IdentityData:
      required:
      - created
      - id
      - links
      - type
      - updated
      type: object
      properties:
        type:
          type: string
          description: Type, always "identity".
          example: identity
        id:
          type: string
          description: Identity identification.
          example: "61723"
        created:
          type: string
          description: Created date of the identity.
          example: 2019-07-29T07:34:09Z
        updated:
          type: string
          description: Created date of the identity.
          example: 2019-07-29T07:34:09Z
        links:
          $ref: '#/components/schemas/IdentityLinks'
        source:
          type: string
          description: Data source.
          example: web
        fullName:
          type: string
          description: FullName of the identity owner.
        firstName:
          type: string
          description: FirstName of the identity owner.
        lastName:
          type: string
          description: LastName of the identity owner.
        middleName:
          type: string
          description: MiddleName of the identity owner.
        title:
          type: string
          description: Title is the prefix to the name of the identity owner.
        DOB:
          type: string
          description: Date of birth of the identity owner.
        occupationCode:
          type: string
          description: Code relating to the occupation held by the identity owner.
        occupationCodeVersion:
          type: string
          description: Occupation Code Version.
        phoneNumbers:
          type: array
          description: List of phone numbers of the identity owner.
          items:
            type: string
        emails:
          type: array
          description: List of email addresses of the identity owner.
          items:
            type: string
        physicalAddresses:
          type: array
          description: List of physical addresses of the identity owner.
          items:
            $ref: '#/components/schemas/PhysicalAddressData'
        organisation:
          type: object
          properties:
            agentFirstName:
              type: string
              description: Agent first name.
            agentLastName:
              type: string
              description: Agent last name.
            agentRole:
              type: string
              description: Agent role.
            businessName:
              type: string
              description: Business name.
            legalName:
              type: string
              description: Legal name.
            shortName:
              type: string
              description: Short name.
            abn:
              type: string
              description: Australian Business Number.
            acn:
              type: string
              description: Australian Company Number.
            isACNCRegistered:
              type: boolean
              description: Indicates whether is Australian Company Number registered.
            industryCode:
              type: string
              description: Industry Code.
            industryCodeVersion:
              type: string
              description: Industry Code Version.
            organisationType:
              type: string
              description: Organisation Type.
            registeredCountry:
              type: string
              description: Registered Country.
          description: Organisation data.
    PhysicalAddressData:
      type: object
      properties:
        type:
          type: string
          description: Physical Address Type.
        addressLine1:
          type: string
          description: AddressLine1.
        addressLine2:
          type: string
          description: AddressLine2.
        addressLine3:
          type: string
          description: AddressLine3.
        postcode:
          type: string
          description: Postcode.
        city:
          type: string
          description: City.
        state:
          type: string
          description: State.
        country:
          type: string
          description: Country.
        countryCode:
          type: string
          description: Country Code.
        formattedAddress:
          type: string
          description: Formatted Address.
    IdentityLinks:
      required:
      - job
      - self
      type: object
      properties:
        self:
          type: string
          description: Self link to the requested identity
          example: https://au-api.basiq.io/users/cd6fbd92/identities/ea3a81
        job:
          type: string
          description: Link to the job associated with this identity
          example: https://au-api.basiq.io/users/ea3a81/connection/s55bf3
    ForbiddenAccessError:
      required:
        - correlationId
        - data
        - type
      type: object
      properties:
        type:
          type: string
          description: Always "list".
          example: list
        correlationId:
          type: string
          description: Unique identifier for this particular occurrence of the problem.
          example: ac5ah5i
        data:
          type: array
          description: Error data.
          items:
            required:
              - code
              - source
              - type
            type: object
            properties:
              type:
                type: string
                description: Type of the response, always "error"
                example: error
              title:
                type: string
                description: Title of the error
                example: Forbidden Access
              code:
                type: string
                description: Application-specific error code, expressed as a string value.
                example: forbidden-access
                enum:
                  - forbidden-access
                  - no-production-access
                  - access-denied
              detail:
                type: string
                description: >-
                  Human-readable explanation specific to this occurrence of the
                  problem.
                example: Access to this resource is forbidden.
              source:
                $ref: '#/components/schemas/Source'
    InternalServerError:
      required:
        - correlationId
        - data
        - type
      type: object
      properties:
        type:
          type: string
          description: Always "list".
          example: list
        correlationId:
          type: string
          description: Unique identifier for this particular occurrence of the problem.
          example: ac5ah5i
        data:
          type: array
          description: Error data.
          items:
            required:
              - code
              - type
            type: object
            properties:
              code:
                type: string
                description: Application-specific error code, expressed as a string value.
                example: internal-server-error
                enum:
                  - internal-server-error
              detail:
                type: string
                description: >-
                  Human-readable explanation specific to this occurrence of the
                  problem.
                example: Internal Server error. Contact support.
              title:
                type: string
                description: Title of the error
                example: Internal Server error.
              type:
                type: string
                description: Type of the response, always "error"
                example: error
    NotFoundError:
      required:
        - correlationId
        - data
        - type
      type: object
      properties:
        type:
          type: string
          description: Always "list".
          example: list
        correlationId:
          type: string
          description: Unique identifier for this particular occurrence of the problem.
          example: ac5ah5i
        data:
          type: array
          description: Error data.
          items:
            required:
              - code
              - type
            type: object
            properties:
              code:
                type: string
                description: Application-specific error code, expressed as a string value.
                example: resource-not-found
                enum:
                  - resource-not-found
              detail:
                type: string
                description: >-
                  Human-readable explanation specific to this occurrence of the
                  problem.
                example: Resource not found.
              title:
                type: string
                description: Title of the error
                example: Requested resource is not found.
              type:
                type: string
                description: Type of the response, always "error"
                example: error
    Source:
      title: Source
      type: object
      properties:
        parameter:
          type: string
          description: String indicating which URI query parameter caused the error.
          example: id
      description: An object containing references to the source of the error.
  securitySchemes:
    services_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - services_token: []
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl
    - node
    - ruby
    - javascript
    - python
