name: Deploy Dev

# Trigger workflow for every push to the `DX-dev` branch
on:
  push:
    branches:
      - DX-dev
  workflow_dispatch:
    inputs:
      deploy_tag:
        description: "Input tag version to deploy"
        required: true
        default: ""

jobs:
  lint-webhooks:
    name: Lint Webhooks File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Lint Webhooks File
        run: npx @redocly/cli lint ./draft-release/webhooks.yml

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: lint-webhooks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Validating Webhooks
        uses: readmeio/rdme@51a80867c45de15e2b41af0c4bd5bbc61b932804
        with:
          rdme: openapi ./draft-release/webhooks.yml --key=${{ secrets.README_API_KEY_DEV }} --id=64658fd7edca4d06be4c77d9
      - name: Validating Enrich
        uses: readmeio/rdme@51a80867c45de15e2b41af0c4bd5bbc61b932804
        with:
          rdme: openapi ./draft-release/enrich.yml --key=${{ secrets.README_API_KEY_DEV }} --id=64658fd7edca4d06be4c77d9

      - name: Validating Identity
        uses: readmeio/rdme@51a80867c45de15e2b41af0c4bd5bbc61b932804
        with:
          rdme: openapi ./draft-release/identity.yml --key=${{ secrets.README_API_KEY_DEV }} --id=64658fd7edca4d06be4c77d9
