name: Deploy Dev

# Trigger workflow for every push to the `DX-dev` branch
on:
  push:
    branches:
      - DX-dev
  workflow_dispatch:
    inputs:
      deploy_tag:
        description: "Input tag version to deploy"
        required: true
        default: ""

jobs:
  pr-lint:
    name: PR Linting
    runs-on: ubuntu-latest
    steps:
      - uses: seferov/pr-lint-action@2f6ccc0e32d53505ab87d1340a8b5c42cb874bd6 # v1.2.0
        with:
          title-regex: '^(DX|DSO|Bump).+'
          title-regex-flags: 'g'
          error-message: 'Add Jira ID to your title in the correct format'

  branch-naming-rules:
    name: Branch Linting
    runs-on: ubuntu-latest
    needs: pr-lint
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(DX|DSO|Bump).+'
          ignore: master,main
          min_length: 2
          max_length: 100

  lint:
    name: Lint Webhooks File
    runs-on: ubuntu-latest
    needs: branch-naming-rules
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Lint Webhooks File
        run: npx @redocly/cli lint ./draft-release/webhooks.yml

  DeployDev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout this repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.5

      - name: Validating Webhooks
        uses: readmeio/rdme@51a80867c45de15e2b41af0c4bd5bbc61b932804 # v8
        with:
          rdme: openapi ./draft-release/webhooks.yml --key=${{ secrets.README_API_KEY_DEV }} --id=${{ secrets.WEBHOOK_API_DEFINITION_ID }}
