name: Deploy Dev

# Run workflow for every push to the `Dev` branch
on:
  push:
    branches:
      - DX-dev
 
  workflow_dispatch:
    inputs:
      deploy_tag:
        description: "Input tag version to deploy"
        required: true
        default: ""

jobs:
  DeployDev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.5

      - name: Validating Webhooks
        uses: readmeio/rdme@51a80867c45de15e2b41af0c4bd5bbc61b932804 # v8
        with:
          rdme: openapi ./draft-release/webhooks.yml --key=${{ secrets.README_API_KEY_DEV }} --id=${{ secrets.WEBHOOK_API_DEFINITION_ID }}
