name: Deploy Prod

# Run workflow for for an input.
on:
  workflow_dispatch:
    inputs:
      deploy_tag:
        description: "Input tag version to deploy"
        required: true
        default: ""

permissions:
  id-token: write
  pull-requests: write
  contents: write

env:
  PAT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  DeployProd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.5

      # Run GitHub Action to sync OpenAPI file at ./core.yml
      - name: Checking Core
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@d5104e5cef6360801167c6cdb73cd03775975804 # v8
        with:
          rdme: openapi ./core.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.CORE_API_DEFINITION_ID }}

      # Run GitHub Action to sync OpenAPI file at ./data.yml
      - name: Checking Data
        uses: readmeio/rdme@d5104e5cef6360801167c6cdb73cd03775975804 # v8
        with:
          rdme: openapi ./data.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.DATA_API_DEFINITION_ID }}

      # Run GitHub Action to sync OpenAPI file at ./identity.yml
      - name: Checking Identity
        uses: readmeio/rdme@d5104e5cef6360801167c6cdb73cd03775975804 # v8
        with:
          rdme: openapi ./identity.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.IDENTITY_API_DEFINITION_ID }}

      # Run GitHub Action to sync OpenAPI file at ./reports.yml
      - name: Checking REPORTING
        uses: readmeio/rdme@d5104e5cef6360801167c6cdb73cd03775975804 # v8
        with:
          rdme: openapi ./reports.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.REPORTS_API_DEFINITION_ID }}
      
      # Run GitHub Action to sync OpenAPI file at ./webhooks.yml
      - name: Checking Webhooks
        uses: readmeio/rdme@d5104e5cef6360801167c6cdb73cd03775975804 # v8
        with:
          rdme: openapi ./webhooks.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.WEBHOOKS_API_DEFINITION_ID }}

      # Run GitHub Action to sync OpenAPI file at ./enrich.yml
      - name: Checking Enrich
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@d5104e5cef6360801167c6cdb73cd03775975804 # v8
        with:
          rdme: openapi ./enrich.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.ENRICH_API_DEFINITION_ID }}
      
      # Run GitHub Action to sync OpenAPI file at ./affordability.yml
      - name: Checking Affordability
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@d5104e5cef6360801167c6cdb73cd03775975804 # v8
        with:
          rdme: openapi ./affordability.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.AFFORDABILITY_API_DEFINITION_ID }} 

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          webhook-type: 'incoming-webhook' # Explicitly define the webhook type
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }} actor:${{ github.actor }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URLS }}
