name: Deploy Prod

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  pull-requests: write
  contents: write

env:
  PAT_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  DeployProd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5

      # Run GitHub Action to sync OpenAPI file at ./core.yml
      - name: Checking Core
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@9fc7a0ff9bac4cb539095cfa2f5eeec6cba48f16 # v8
        with:
          rdme: openapi ./core.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.CORE_API_DEFINITION_ID }}

      # Run GitHub Action to sync OpenAPI file at ./data.yml
      - name: Checking Data
        uses: readmeio/rdme@9fc7a0ff9bac4cb539095cfa2f5eeec6cba48f16 # v8
        with:
          rdme: openapi ./data.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.DATA_API_DEFINITION_ID }}

      # Run GitHub Action to sync OpenAPI file at ./identity.yml
      - name: Checking Identity
        uses: readmeio/rdme@9fc7a0ff9bac4cb539095cfa2f5eeec6cba48f16 # v8
        with:
          rdme: openapi ./identity.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.IDENTITY_API_DEFINITION_ID }}

      # Run GitHub Action to sync OpenAPI file at ./reports.yml
      - name: Checking Reports
        uses: readmeio/rdme@9fc7a0ff9bac4cb539095cfa2f5eeec6cba48f16 # v8
        with:
          rdme: openapi ./reports.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.REPORTS_API_DEFINITION_ID }}

      # Run GitHub Action to sync OpenAPI file at ./affordability.yml
      - name: Checking Affordability
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@9fc7a0ff9bac4cb539095cfa2f5eeec6cba48f16 # v8
        with:
          rdme: openapi ./affordability.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.AFFORDABILITY_API_DEFINITION_ID }}

      # Run GitHub Action to sync OpenAPI file at ./enrich.yml
      - name: Checking Enrich
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@9fc7a0ff9bac4cb539095cfa2f5eeec6cba48f16 # v8
        with:
          rdme: openapi ./enrich.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.ENRICH_API_DEFINITION_ID }}

      # Run GitHub Action to sync OpenAPI file at ./payments.yml
      - name: Checking Payments
        uses: readmeio/rdme@9fc7a0ff9bac4cb539095cfa2f5eeec6cba48f16 # v8
        with:
          rdme: openapi ./payments.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.PAYMENTS_API_DEFINITION_ID }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1 # Leverages SemVer as per https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }} actor:${{ github.actor }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URLS }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK