name: PR and Branch linting

on:
  pull_request:
    types: ['opened', 'edited']
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  pr-lint:
    name: PR Linting
    runs-on: ubuntu-latest
    steps:
      - uses: seferov/pr-lint-action@2f6ccc0e32d53505ab87d1340a8b5c42cb874bd6 # v1.2.0
        with:
          title-regex: '^(DX|DSO|Bump).+' # Supports either DEVX prefixed PRs
          title-regex-flags: 'g' # optional
          error-message: 'Add Jira ID to your title in the correct format'

  branch-naming-rules:
    name: Branch Linting
    runs-on: ubuntu-latest
    needs: pr-lint # Ensure this runs only after `pr-lint` completes successfully
    steps:
      - uses: deepakputhraya/action-branch-name@master # Use the latest version
        with:
          regex: '^(DX|DSO|Bump).+' # Supports either DEVX prefixed Branches
          ignore: master,main # Ignore exactly matching branch names from convention
          min_length: 2 # Min length of the branch name
          max_length: 100 # Max length of the branch name

  lint:
    runs-on: ubuntu-latest
    needs: branch-naming-rules # Ensure this runs only after `branch-naming-rules` completes successfully
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Lint Files
        run: |
          lint_files=("core.yml" "data.yml" "services.yml" "reports.yml" "affordability.yml" "enrich.yml" "identity.yml" "webhooks.yml")
          for file in "${lint_files[@]}"; do
            result=$(npx @redocly/cli lint "$file" --format=json | jq '.warnings | length')
            echo "::set-output name=${file}-warnings::$result"
          done

      - name: Aggregate Warning Counts
        id: aggregate-warnings
        run: |
          lint_files=("core.yml" "data.yml" "services.yml" "reports.yml" "affordability.yml" "enrich.yml" "identity.yml" "webhooks.yml")
          total_warnings=0
          summary="Linting Warnings Summary:\n"
          for file in "${lint_files[@]}"; do
            count=$(jq -r ".${file}-warnings" <<< "${{ steps.lint.outputs }}")
            total_warnings=$((total_warnings + count))
            summary+="$file: $count warnings\n"
          done
          echo "TOTAL_WARNINGS=$total_warnings" >> $GITHUB_ENV
          echo "SUMMARY=$summary" >> $GITHUB_ENV

      - name: Send Slack Notification if Warnings Exist
        if: env.TOTAL_WARNINGS > 0
        uses: slackapi/slack-github-action@v2
        with:
          webhook-type: 'incoming-webhook'
          payload: |
            {
              "text": "Linting Warnings Detected",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Linting Notification",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Linting Warnings Detected* in GitHub Actions :warning:\n*Total Warnings:* ${{ env.TOTAL_WARNINGS }}\n\n*Details:*\n${{ env.SUMMARY }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Please review the warnings and take appropriate actions."
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
