name: PR and Branch linting

on:
  pull_request:
    types: ['opened', 'edited']

jobs:
  pr-lint:
    name: PR Linting
    runs-on: ubuntu-latest
    steps:
    - uses: seferov/pr-lint-action@2f6ccc0e32d53505ab87d1340a8b5c42cb874bd6 # v1.2.0
      with:
        title-regex: '^(DX|DSO).+' # Supports either DEVX prefixed PRs
        title-regex-flags: 'g' # optional
        error-message: 'Add Jira ID to your title in the correct format'
  branch-naming-rules:
    name: Branch Linting
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@e0f8db53a8e289f1ae6f6c3e8dc70a3d366fd876 #v1.0.0
        with:
          regex: '^(DX|DSO).+' # Supports either DEVX prefixed Branches
          ignore: master,main # Ignore exactly matching branch names from convention
          min_length: 2 # Min length of the branch name
          max_length: 500 # Max length of the branch name
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Use the Node.js version compatible with Redocly CLI

    - name: Install Redocly CLI
      run: npm install -g @redocly/openapi-cli
    
    - name: Verify Redocly CLI Installation
      run: npx redocly --version
      
    - name: Lint YAML Files
      run: npx redocly lint

    - name: Send custom JSON data to Slack workflow
      if: failure() # This step will run only if the previous step fails
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      with:
        payload: |
          {
            "text": "Linting Failed in GitHub Actions",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Linting Failure Notification",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Linting Failed* in GitHub Actions :x:\n*Repository:* <${{ github.repository_url }}|${{ github.repository }}>\n*Actor:* ${{ github.actor }}\n*Pull Request:* <${{ github.event.pull_request.html_url }}|PR Link>\n*Commit:* <${{ github.event.head_commit.url }}|Commit Link>"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Please review the PR and make necessary changes."
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URLS }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        
