name: PR and Branch linting

on:
  pull_request:
    types: ['opened', 'edited']
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  pr-lint:
    name: PR Linting
    runs-on: ubuntu-latest
    steps:
      - uses: seferov/pr-lint-action@2f6ccc0e32d53505ab87d1340a8b5c42cb874bd6 # v1.2.0
        with:
          title-regex: '^(DX|DSO|Bump).+' # Supports either DEVX prefixed PRs
          title-regex-flags: 'g' # optional
          error-message: 'Add Jira ID to your title in the correct format'

  branch-naming-rules:
    name: Branch Linting
    runs-on: ubuntu-latest
    needs: pr-lint # Ensure this runs only after `pr-lint` completes successfully
    steps:
      - uses: deepakputhraya/action-branch-name@master # Use the latest version
        with:
          regex: '^(DX|DSO|Bump).+' # Supports either DEVX prefixed Branches
          ignore: master,main # Ignore exactly matching branch names from convention
          min_length: 2 # Min length of the branch name
          max_length: 100 # Max length of the branch name

  lint:
    runs-on: ubuntu-latest
    needs: branch-naming-rules # Ensure this runs only after `branch-naming-rules` completes successfully
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js 20

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Verify Redocly CLI Installation
        run: npx @redocly/cli --version

      - name: Lint Core
        id: lint-core
        run: npx @redocly/cli lint core.yml
        continue-on-error: true # Allow the workflow to continue even if this step fails

      - name: Lint data
        id: lint-data
        run: npx @redocly/cli lint data.yml
        continue-on-error: true # Allow the workflow to continue even if this step fails

      - name: Lint Services 
        id: lint-services
        run: npx @redocly/cli lint services.yml
        continue-on-error: true # Allow the workflow to continue even if this step fails

      - name: Lint Reports 
        id: lint-reports
        run: npx @redocly/cli lint reports.yml
        continue-on-error: true # Allow the workflow to continue even if this step fails

      - name: Lint affordability 
        id: lint-affordability
        run: npx @redocly/cli lint affordability.yml
        continue-on-error: true # Allow the workflow to continue even if this step fails

      - name: Lint Enrich
        id: lint-enrich
        run: npx @redocly/cli lint enrich.yml
        continue-on-error: true # Allow the workflow to continue even if this step fails

      - name: Lint Identity 
        id: lint-identity
        run: npx @redocly/cli lint identity.yml
        continue-on-error: true # Allow the workflow to continue even if this step fails

      - name: Lint Webhooks 
        id: lint-webhooks
        run: npx @redocly/cli lint webhooks.yml
        continue-on-error: true # Allow the workflow to continue even if this step fails

      - name: Check for Linting Warnings
        id: check-lint-warnings
        run: |
          warnings=0
          if [[ "${{ steps.lint-core.outputs.warnings }}" != "" ]]; then
            warnings=1
          fi
          if [[ "${{ steps.lint-data.outputs.warnings }}" != "" ]]; then
            warnings=1
          fi
          if [[ "${{ steps.lint-services.outputs.warnings }}" != "" ]]; then
            warnings=1
          fi
          if [[ "${{ steps.lint-reports.outputs.warnings }}" != "" ]]; then
            warnings=1
          fi
          if [[ "${{ steps.lint-affordability.outputs.warnings }}" != "" ]]; then
            warnings=1
          fi
          if [[ "${{ steps.lint-enrich.outputs.warnings }}" != "" ]]; then
            warnings=1
          fi
          if [[ "${{ steps.lint-identity.outputs.warnings }}" != "" ]]; then
            warnings=1
          fi
          if [[ "${{ steps.lint-webhooks.outputs.warnings }}" != "" ]]; then
            warnings=1
          fi
          echo "warnings=$warnings" >> $GITHUB_ENV
        continue-on-error: true
      

      - name: Send Slack Notification if Warnings Exist
        if: ${{ steps.check-lint-warnings.outputs.warnings == '1' }}
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          webhook-type: 'incoming-webhook' # Explicitly define the webhook type
          payload: |
            {
              "text": "Linting Warnings or Errors in GitHub Actions",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Linting Notification",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Linting Warnings Detected* in GitHub Actions :warning:\n*Repository:* ${{ github.repository }}\n*Actor:* ${{ github.actor }}\n*Pull Request:* <${{ github.event.pull_request.html_url }}|PR Link>"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Please review the PR and make necessary changes."
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URLS }}
