name: PR and Branch linting

on:
  pull_request:
    types: ['opened', 'edited']

jobs:
  pr-lint:
    name: PR Linting
    runs-on: ubuntu-latest
    steps:
    - uses: seferov/pr-lint-action@v1.1.2
      with:
        title-regex: '^(DEVX|Dev)-.+' # Supports either DSO prefixed PRs
        title-regex-flags: 'g' # optional
        error-message: 'Add Jira ID to your title in the correct format'
  branch-naming-rules:
    name: Branch Linting
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: '^(DEVX|Dev)-.+' # Supports either DSO prefixed Branches
          ignore: master,main # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 100 # Max length of the branch name