name: Deploy Dev

# Run workflow for every push to the `Dev` branch
on:
  push:
    branches:
      - DX-dev

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5

      # Run GitHub Action to sync OpenAPI file at ./core.yml
      - name: Checking Core
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@9824100d73c58e58adc52d80ac2c6fc4f96caabf # v8
        with:
          rdme: openapi ./draft-release/core.yml --key=${{ secrets.README_API_KEY_DEV }} --id=${{ secrets.CORE_DEV_API_DEFINITION_ID }}

